# Generated by Django 3.1 on 2021-03-17 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210314_1421'),
        ('cart', '0002_remove_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='main.course'),
        ),
    ]
